include:
  - project: 'general/ci-templates'
    file: 'workflow.gitlab-ci.yml'
  - project: 'general/ci-templates'
    file: 'yarn.gitlab-ci.yml'
  - project: 'general/ci-templates'
    file: 'docker-img.gitlab-ci.yml'
  - project: 'general/ci-templates'
    file: 'deployment-api.gitlab-ci.yml'


variables:
  DEPLOYMENT_SPEC_FILE: 'docker-deployment.yml'
  DEPLOYMENT_SPEC_NAME_STAGING: 'gesetzebuch_web'
  DEPLOYMENT_AUTO_STAGING: 'yes'


terminal:
  # This can be any image that has the necessary runtime environment for your project.
  image: node:10-alpine
  before_script:
    - apk update
  script: sleep 60
  variables:
    RAILS_ENV: "test"
    NODE_ENV: "test"
