include:
  - project: 'general/ci-templates'
    file: 'workflow.gitlab-ci.yml'
  - project: 'general/ci-templates'
    file: 'yarn.gitlab-ci.yml'
  - project: 'general/ci-templates'
    file: 'docker.gitlab-ci.yml'
